### ISSUE TITLE
How to handle release announcements?

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy-website#1]
I think it would be good to have some release announcements for minor versions (but not bug fix releases) on the page. Could be a sections "Releases" or "News" with a corresponding link on the homepage.

**Comment by pstjohn** [comment]
And in general maintain a changelog for major releases 😄 .

**Comment by hredestig** [comment]
How easy is it to automate the build process? Placing the release notes in the tag annotation seems a good place, then we the site is generated, could just grab the last couple of release tags? Could make a template for what they should look like syntax etc.

**Comment by cdiener** [comment]
So Hugo can [generate context from web requests](https://gohugo.io/extras/datadrivencontent/) at the time of build but I was thinking something more complete, maybe including some code examples highlighting the changes. Github releases are usually a bit more concise. For instance for the 0.6 release we might want to highlight the conetxt managers and new functionalities. For now I was just thinking about copying the major release notes (is already markdown) and adding more info in a content file for hugo. I don't know you tell me what you consider best.

**Comment by pstjohn** [comment]
Where do the release notes currently live?

**Comment by cdiener** [comment]
I think nowhere, because there are none :open_mouth:

**Comment by pstjohn** [comment]
oh gotcha, I thought you meant there were markdown notes already.

We might want to copy the format of something like [numpy](https://github.com/numpy/numpy/tree/master/doc/release), (fairly detailed) or [sklearn](https://github.com/scikit-learn/scikit-learn/blob/master/doc/whats_new.rst)?

**Comment by cdiener** [comment]
Both are excellent examples IMO. Maybe have the webpage in a more casual style with more examples? Or should that be left for docs?

**Comment by pstjohn** [comment]
I'd say probably docs.. Regardless I'd like to have more examples on there of people using the package to do analysis, and for new features we could include those types of stories.

We could certainly link them more informally on the website, and in general having a 'news' feed isn't the worst idea (highlight pubs, presentations, new features, etc.)

**Comment by cdiener** [comment]
Cool. So we would have release notes (also on the webpage?) and a news section where we can highlight features etc. (needs to be update constantly or it makes the project look dead).

**Comment by Midnighter** [comment]
What about instead of (or in addition to) having news, we have a cookbook on the website that basically has static renders of notebooks with the examples?

**Comment by pstjohn** [comment]
I think that's probably better suited for the readthedocs page? But I'm entirely on board for having that type of information somewhere, I would just think it might be better to have the documentation in one place.

**Comment by hredestig** [comment]
The numpy style release notes strikes me as a good idea and also a notebook that exemplifies the major user-level changes. Also keeping doc on the website up-to-date seems good but I fear that the overhead comes with the risk that it doesn't happen.. Perhaps an auto-generated link to the release notes or hugo can pull in the latest release notes and render them in a nice way + a link the the recent_changes.ipynb that we then also maintain on readthedocs.

**Comment by cdiener** [comment]
@hredestig yes that would be possible, like https://atom.io/releases, correct? Only thing is that this will only be updated at build so new releases might not appear on the page until we rebuild it.

**Comment by hredestig** [comment]
Yes either like that, taking the git tag, or grabbing the numpy style release document from cobrapy/release-notes. I think having to rebuild the site is acceptable.

**Comment by cdiener** [comment]
I think that would be feasible without too much problems. For the beginning we could just add the release docs as content type by hand (just put the TOML header and copy the markdown). Either way we can also add a badge with the most recent version like [![GitHub release](https://img.shields.io/github/release/opencobra/cobrapy.svg)]() that links to the release notes on github or the notebook.

**Comment by hredestig** [comment]
Any preferences for release notes in rst or md?

**Comment by Midnighter** [comment]
`.md` for simplicity if we don't need the larger feature set?

**Comment by cdiener** [comment]
MD will be easier to maintain on the website.

**Comment by cdiener** [comment]
Okay what I ended up with for now is to have only the latest patch for each minor versions more or less (like 0.6.0 and 0.5.11) because those are the only ones that have release notes. Maybe would be better just to have it as 0.6, 0.5, etc. or also write "real" release notes for patch versions (and not just copy the release notes from the minor version).

**Comment by hredestig** [comment]
I think we can have release notes also for patch versions.. but not pre-releases, those are built incrementally until the final release number.

**Comment by cdiener** [comment]
Sounds good. In that case I would vote that the patch notes only include the fixes/features of that particular patch and the first release note the entire set of new features. Alternatively we could also visually distinguish release notes for minor releases (0.6, 0.5, etc) on the website so there is a clear distinction between release and patch.

**Comment by hredestig** [comment]
:+1: to that, each release note only contain the changes made in that particular release.

**Comment by cdiener** [comment]
The currently implemented spec is outlined in [here](https://github.com/opencobra/cobrapy-website/blob/master/data/releases.yml). Closing for now.
