### ISSUE TITLE
Add a deploy token to the secrets

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy-website#21]
Hi @Midnighter,

since I don't have admin rights here anymore, can you add a valid personal access token (prob from the bot) to the repo settings? Name should be `PERSONAL_TOKEN`.

Thanks!

**Comment by Midnighter** [comment]
What scope(s) does the token need, i.e., what is it intended for?

**Comment by cdiener** [comment]
Push from here to the cobrapy gh-pages branch.

**Comment by Midnighter** [comment]
Ah, cool. Are you moving things from Travis to GitHub Actions? Anyway, I've added a token with `public_repo` scope from the bot for this repo. That is what the token on Travis CI had. Please let me know if more privileges are needed.

**Comment by cdiener** [comment]
Yep, exactly. Moving to Actions. Thanks!

**Comment by Midnighter** [comment]
I guess we should test this once and then I can remove the Travis integration.

**Comment by cdiener** [comment]
Ups, already removed it. And it worked. I just adjusted the user name so it will show up as the bot.
