### ISSUE TITLE
Directions for adding a new publication

### ISSUE THREAD

**Issue by mmundy42** [opencobra/cobrapy-website#4]
Are there directions for adding a new publication? It looks like the "articles.xml" needs to be updated. Is there an easy way to generate the XML for a publication?

**Comment by cdiener** [comment]
Actually the XML is just the output from Pubmed which can be parsed by the python script in the repo to create the hugo markdown files. This is only used to semi-automatically add all articles from Pubmed that cited the original cobrapy publication. If you want to add an article by hand you just need to create a new file in `content/pubs` and fill in the required fields.

For instance you might create a file `content/pubs/mikes_publication.md` with the following text:

```markdown
+++
authors = ["First Author", "Second Author"]
title = ""
journal = ""
what = "article"
doi = "10.1186/1752-0509-7-74"
pubmed = "ID"
date = ""
+++

Put the abstract here.
```

Note that `date` should be the date of publication.

Hope that helps, I will update the Readme with some instructions on how to add publications and packages.

**Comment by mmundy42** [comment]
How do you want to handle updates in git? There aren't any forks of the repo yet. Is it OK to push a new branch on this repo? Or would you prefer a pull request from a fork?

**Comment by cdiener** [comment]
I think from a fork like @pstjohn did it in his PR would be fine.

**Comment by cdiener** [comment]
Ok, your changes have now propagated to the website and I have added a section in the Readme. Sorry if you received a comment for me asking for license, did not see them at first :sweat_smile:
