### ISSUE TITLE
Add bleeding-edge install instructions?

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy-website#8]
Could be useful to add 

```
pip install git+https://github.com/opencobra/cobrapy@devel
```

as an install option. It's a snippet I use occasionally to put cobrapy in non-development virtualenvs.

**Comment by pstjohn** [comment]
On second thought, that doesn't appear to install LP solvers...

**Comment by Midnighter** [comment]
I usually prefer installing another way:
```
pip install https://github.com/opencobra/cobrapy/archive/devel.zip
```
since GitHub just zips the latest working tree and it doesn't clone the whole repo first (faster). It does install swiglpk.

**Comment by hredestig** [comment]
The only consideration I would have is that by telling users this is a way to stay up to date with the very latest release, then people might do that as default and then not fully realizing that it's unstable..

**Comment by Midnighter** [comment]
It might be too much effort for too little gain but we could be more dilligent about pre-releases such that if you want to live life on the cutting edge you can always `pip install --pre cobra`. It would add to our workload, though, and I don't know what the actual interest by users would be.
